### ISSUE TITLE
[BUG] Remove the "Play" option as it doesn't align time properly

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/EML-Water-Portal#11]
![Screenshot 2024-08-05 at 09 35 50](https://github.com/user-attachments/assets/823f19f1-3aca-4657-a21c-b0f48d70c4c4)

**Comment by pierreleripoll** [comment]
@charlottegiseleweil I don't have the problem locally, still remove it ?

**Comment by charlottegiseleweil** [comment]
@pierreleripoll Not priority don't worry - leave as is until you're back next week and we'll investigate then ?

(if you want to do one quick thing though : the remaning task (first checkbox) of #3 would be helpful for this first prototype!)

**Comment by charlottegiseleweil** [comment]
ok to keep if functional - can you just replace the "Play" button by a play arrow to minimize useless text in the UI @pierreleripoll ?
