### ISSUE TITLE
[FEAT] Layout fixes for Overall UI

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/EML-Water-Portal#16]
- [x] Timerange at the bottom should be fixed - we'd only scroll the "Lineplots" section
- [x] Height of lineplots should be smaller, to minimize scrolling.
- [x] The left menu should only appear within the map section, as described in initial mock-up (see #2 )
- [x] Remove "About" tab (will be in the (i) dialog from the left). Hence remove the "Home" tab as well as it's a single-tab website.
- [x] Fix the fact that EPFL logo appears twice (right and left) in the top menu bar. Right is enough.
- [ ] #42
- [ ] #33

**Comment by charlottegiseleweil** [comment]
@pierreleripoll I don't understand why these last two feature requests are now considered outdated. 

- UI layout needs to be updated based on the decision of minimizing the map. 
- Colorscale feature has been moved to #33

**Comment by pierreleripoll** [comment]
@charlottegiseleweil it was following a discussion with @ymarcon !

**Comment by charlottegiseleweil** [comment]
Moved both remaining points to new issues as discussed.
