### ISSUE TITLE
[ENHANCEMENT] Undersample data with zoom level 

### ISSUE THREAD

**Issue by pierreleripoll** [EPFL-ENAC/EML-Water-Portal#18]
Right now, we have a 15-minute time step for data acquisition, even when the time range is filtered to the maximum. This results in a large number of points being rendered in charts (4 per hour * 24 hours per day * 365 days a year * 2 years = 70,000 data points per line).

What would be ideal is to undersample the data when zooming out with the time range selector.

**Comment by ymarcon** [comment]
If backend is prometheus based, here is the API to query a time range:
https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries

**Comment by pierreleripoll** [comment]
@ymarcon I think the prometheus based "step" feature is nice to improve loading time for the whole dataset (might be massive) but my suggestion is more for visualisation itself : performance-wise echarts is not so strong re-rendering many points in line charts, so even when the dataset is _loaded_ in the browser we might need to undersample data given to echarts

**Comment by pierreleripoll** [comment]
I greatly improved charts performance with 45ae931 so closing this issue, feel free to reopen it once we have access to real data if needed
