### ISSUE TITLE
Map takes to much space in width

### ISSUE THREAD

**Issue by ymarcon** [EPFL-ENAC/EML-Water-Portal#29]
Review layout so that it is smaller for the benefit of the charts (full height)

**Comment by ymarcon** [comment]
@AnderssonDan-epfl new layout ok?

![image](https://github.com/user-attachments/assets/11e3b190-b5b5-4f57-9589-cfee5e50daae)

**Comment by AnderssonDan-epfl** [comment]
> @AnderssonDan-epfl new layout ok?
> 
> ![image](https://private-user-images.githubusercontent.com/2581149/359969422-11e3b190-b5b5-4f57-9589-cfee5e50daae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMDc2NDQsIm5iZiI6MTcyNDMwNzM0NCwicGF0aCI6Ii8yNTgxMTQ5LzM1OTk2OTQyMi0xMWUzYjE5MC1iNWI1LTRmNTctOTU4OS1jZmVlNWU1MGRhYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjJUMDYxNTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRkMmYwZDlmOWY1YThkMGVjODYyNzQ1Mjc5ZTkyMTM5ZTEwYjBlYzAxNDU3YWM4MTJkNDg3YThmOWVhYzJkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vw9VNbaWS6KwpDBzpPP5DgVr28clhB38hpA2-OtzwBc)

@ymarcon This is perfect, thank you very much!
