### ISSUE TITLE
[FEAT] LINEPLOTS Component

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/EML-Water-Portal#3]
- [x] Variables are ordered : 
* following order from top to bottom: Water level, water temperature, electrical conductivity (rather than specific electro-conductivity), dissolve oxygen, pH, turbidity, oxidation-reduction potential, air temperature.
* Default open should be the top two: water level and water temperature. Rest collapsed by default
- [x] line plot collapses/expands upon clicking on variable name
- [x] Lineplots draft
- [x] tooltip that displays details and aligns time for all subplots : Line plots with time always aligned, like in https://wanh.epfl.ch/Home --> @pierreleripoll : Align times for all lineplots => moved to #12 
- [x] Timeframe selector (at the bottom, like in [pneuma](https://pneuma-dev.epfl.ch/). @pierreleripoll : Extract timerange filter from lineplots to be common to all.

**Comment by RizlanBL** [comment]
About the scale of the line plots. Is there a way to vary the scale manually? Or can the scale adjust automatically to the data range for a given time range? Thanks.

**Comment by charlottegiseleweil** [comment]
So ideally the scale adjusts to the data range selected right ?

**Comment by RizlanBL** [comment]
exactly

**Comment by pierreleripoll** [comment]
Hi @RizlanBL,

I have a few questions regarding the units and precision for each plot:

1. **Units**: 
    - What are the units for each measurement? For example:
        - Water level: meters (m) or percentage (%)?
        - Dissolved oxygen: milligrams per liter (mg/L) or percentage (%)?
    - Could you specify the units for the other measurements as well?

2. **Precision**:
    - How many decimal places should we retain? For instance, the Bn sensors show values with up to 13 decimal places, which seems excessive.
    - What is the sensitivity of your sensors?

Knowing this will help us optimize the visualizations and improve performance.

Thanks!

**Comment by charlottegiseleweil** [comment]
@pierreleripoll for units, please see the data for description of each variables in sample data here #1

**Comment by charlottegiseleweil** [comment]
mostly fixed by #10 - just need re-ordering of variables (first checkbox) pls @pierreleripoll

**Comment by AnderssonDan-epfl** [comment]
> Hi @RizlanBL,
> 
> I have a few questions regarding the units and precision for each plot:
> 
> > 1. **Units**:
> >    
> >    * What are the units for each measurement? For example:
> >      
> >      * Water level: meters (m) or percentage (%)?
> >      * Dissolved oxygen: milligrams per liter (mg/L) or percentage (%)?
> >    * Could you specify the units for the other measurements as well?
> 
> Answered by @charlottegiseleweil
> 
> 2. **Precision**:
>    
>    * How many decimal places should we retain? For instance, the Bn sensors show values with up to 13 decimal places, which seems excessive.
>    * What is the sensitivity of your sensors?
> 
> Knowing this will help us optimize the visualizations and improve performance.
> 
> Thanks!

Hi @pierreleripoll 

Here you will find all the units for our parameters: 
- Temperature [°C]
- Dissolved oxygen [mg/L]
- Specific conductivity [µs/cm]
- Turbidity [NTU]
- ORP [mV]
- pH [pH]
- Water level / water depth [m]
- Water flow rate [m^3/s]

Two decimal are sufficient for all parameters, with the exception of water level/water depth, for which three decimal would be sufficient.

Let me know if you have any more questions,

Best, 

Dan

**Comment by charlottegiseleweil** [comment]
moved remaining details in #17
