### ISSUE TITLE
[FEAT] (Filtering) Filtering per sensor type should filter the data in the lineplots

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/EML-Water-Portal#38]

**Comment by ymarcon** [comment]
Then it changes functionality of these buttons: currently it makes sensor type's layer visible or not, which is different from (de)selecting a group of sensors. We cannot have both from these buttons: is that ok?

**Comment by charlottegiseleweil** [comment]
Ok - Hold on this until we review the full design !
