### ISSUE TITLE
[FEAT] Icons for sensors instead of colors ? 

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/EML-Water-Portal#39]
- [ ] Icons : 

A `Opacity`
B `Thermostat` (since these measure temp only)
C `Podcast`
D `InvertColors`

You might also like `WaterDrop`

- [ ] Hover : D icon -> hover upon icon say "Water samples data are available upon request"

**Comment by AnderssonDan-epfl** [comment]
> @AnderssonDan-epfl , do you have in mind some icons that could depict the sensors type A-B-C-D to keep the colors used for variables ? Here's an[ icon library](https://mui.com/material-ui/material-icons/) - and some suggestions :
> 
> A `Opacity` B `Thermostat` (since these measure temp only) C `SensorDoor` D `InvertColors`
> 
> You might also like `WaterDrop`

@charlottegiseleweil I like the icons for A, B and D. For C I think the "Podcast" icon would fit better.
