### ISSUE TITLE
Preprocess data from InfluxDB

### ISSUE THREAD

**Issue by ymarcon** [EPFL-ENAC/EML-Water-Portal#43]
Update: db changed from prometheus to influxdb => following tasks could be outdated 

Preferably in a backend API (i.e. not in the webapp, to allow reduced dataset size and time range filtering):

* merge data into per-sensor dataset: location names with corresponding sensor name (e.g. "3: Principal" and "Principal VuLink" are both sensor A3 in the web interface). VuLink devices are reporting air measures, others are reporting water measures
* transform timestamps format from epoch to string "yyyy-MM-dd HH:mm:ss"
* transform dataset from long format to wide format

**Comment by charlottegiseleweil** [comment]
@ymarcon I believe this is done ? Closing this issue, but please re-open if I'm missing something !
