### ISSUE TITLE
[FEAT] MAP Component

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/EML-Water-Portal#5]
Should include:
- [x]  Basemap (classic)
- [x] Vector layers: pipes, catchments 
- [x] Measurement locations layer (A1, ..) depicting 3 types of sensors differently - with ability to select : 

- Upon hover : Tooltip should appear upon hover
- Upon click : Select/deselect location (greyed out when unselected)

- [x] Centered map lower as the default when one opens the site so that we see the sensors more. So, we see the sensors and the Sorge upon opening.

**Comment by charlottegiseleweil** [comment]
Design question for @carvaEPFL and @RizlanBL - how should sensors be depicted ? (A, B, C, of different types?) - any specific icons that would make sense ?

**Comment by RizlanBL** [comment]
Do you mean on the map? If so, there should be three types of sites. The A sites (A1-A6) that have the In Situ sensors, the B sites (B1-B15) that have temperature only and the C sites (C1 and C2) that are vary close to the A sites and that have water level only. Does that answer your question?

**Comment by RizlanBL** [comment]
One comment on the map. It looks nice just that it would be better to have it centered lower as the default when one opens the site so that we see the sensors more. So, we see the sensors and the Sorge upon opening.

**Comment by pierreleripoll** [comment]
should be fixed by 5e7b18d58bc98e5add46c12dae7b50c61764fbb4
