### ISSUE TITLE
[DESIGN] Lineplots order

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/EML-Water-Portal#7]
Which order do you want the variables in and should each be expanded or collapsed by default?

**Comment by RizlanBL** [comment]
The variables should be in the following order from top to bottom: Water level, water temperature, electrical conductivity (rather than specific electro-conductivity), dissolve oxygen, pH, turbidity, oxidation-reduction potential, air temperature.

**Comment by charlottegiseleweil** [comment]
thanks @RizlanBL - can you add which should be expanded by default when opening the website ? (by default now all are collapsed)

**Comment by RizlanBL** [comment]
This is not about the order but about the scale. Is there a way to vary the scale manually? Or can the scale adjust automatically to the data range for a given time range? Thanks.

**Comment by RizlanBL** [comment]
Default open should be the top two: water level and water temperature.
