### ISSUE TITLE
[PERFORMANCE] Optimize loading time of eCharts 

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/EML-Water-Portal#8]

**Comment by ymarcon** [comment]
Currently data are in CSV files that I stored in the common S3 bucket (see `src/boot/api.ts`) along with a metadata file (`datasets.json`). These are downloaded and parsed by the measures store (`src/stores/measures.ts`), and organized by sensor: one column per measure + the timestamp.

The display in the `TimeseriesChart` echart component is the phase that takes most time.

**Comment by charlottegiseleweil** [comment]
https://github.com/EPFL-ENAC/EML-Water-Portal/commit/74771853c39dbaebde7109381dd35220f22fd286 should have fixed that ! 👏 @pierreleripoll ! 
@ymarcon - please re-open if performance is still not satisfying.
