### ISSUE TITLE
[DESIGN] Specs for the Scenarios section

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/EML-Water-Portal#9]
# Dialog box for each watershed: 
<img width="807" alt="Screenshot 2024-08-08 at 10 40 23" src="https://github.com/user-attachments/assets/dbd7999b-6280-4b1e-bfd5-5a763d6895d0">

### Parameters 
- 3 sliders
- 1 single-select (Vegetation), selection through icons
- 1 multi-select (Water re-use checkboxes)
Precisions coming from researchers (see list below)

Vegetation icons (reference from MaterialIcons, and "hover text"):
```
NotInterestedIcon : "None"
GrassIcon : "Grass"
LocalFloristIcon : "Schrubs"
ParkIcon (or better if we find a willow icon?): "Shallow-rooted tree"
ForestIcon (or better if we find Oak icon?): "Deep-rooted tree"
```

### Results 
- Name of the Scenario: automatically built based on user selections
- Key summary stats : (with up/down arrow). Awaiting Precisions

### "Add scenario" button 
in lieu of "apply"

# behavior (when "Apply scenario")
It would add a *dashed* line (in relevant lineplots) corresponding to the scenario. 
Data will come from Paolo & @carvaEPFL. Fake data for now
Important to have implemented #15 to have the ability to remove scenarios

**Comment by carvaEPFL** [comment]
Flow discharge and Temperature are the outputs at the outlet points, where the water is released into the Sorge River.
Additionally, for scenarios with storage volume, we can show the stored volume with simple rules for its release in time. 
In reality, the volume dynamics in the storage tanks may depend on the season, and the type of use (irrigation, toilet flushing,...)

**Comment by charlottegiseleweil** [comment]
@carvaEPFL , thank you but we'll need a lot more details than that! 😄  such as :
(1) A list of scenarios with each parameter that can change, and the values it can take
(2) The variables that will be updated with an additional line per scenarios, and examples of datasets from these scenarios.
(3) The "user story" on how a user selects one or several scenarios and the constraints on those.

**Comment by charlottegiseleweil** [comment]
# Additonal information we need from researchers 
@AnderssonDan-epfl @RizlanBL 
### Parameters 
- [ ] for all parameters : title (if different from the sketch above), and units. 
- [ ] for all parameters : (i) contents if relevant - to be described in #6 
- [ ] for each slider : default values, extreme values and steps. 

### Results
- [ ] Structure of name of the scenarios (e.g. {Selector} with tank {8m3}, infiltration {40%}).
- [ ] description of key summary statistics (and if you want absolute and/or relative values)

##  And for reference, sktech from Paolo today
For each watershed : Soil, tank, roof :
<img width="1344" alt="Screenshot 2024-08-08 at 09 13 49" src="https://github.com/user-attachments/assets/35280007-d8bb-4158-9583-a4a8047865ae">

**Comment by charlottegiseleweil** [comment]
Hello @AnderssonDan-epfl @RizlanBL you can provide here directly the points raised last week (listed under "Additonal information we need from researchers" in the comment above) when you get a chance ! Thank you very much !

**Comment by AnderssonDan-epfl** [comment]
Hello @charlottegiseleweil,
**Here's a list of things we'd like to see changed on the web page and an image with some information on how we'd like to have it:**.
- The different types of sensor should be able to be activated, as is currently the case for the different layers (we want to be able to remove certain sensors from the map for better visualisation of the sensors we are interested in).
- Modify the sensor labels --> picture below
- Add automatic samplers below the sensors (--> picture below). For these, we would like to have a pop-up information when we click on them with a small description (Laboratory analysis of water samples for heavy metals, tyre abrasion residues and PFAS) and the information that the data from these are only on request (not displayed directly on the website).
- Add dots on the title of the graph with the type of sensors that provide these data --> picture below
- Change the name of the B sensors. It currently goes from B15 (upstream) to B1 (downstream) and we would like to have B1 (upstream) to B15 (downstream).
- Need to add Ijinus C2 sensors
- We want all the sensor points to be visible, without overlapping.
[waterportal_changes.pdf](https://github.com/user-attachments/files/16598880/waterportal_changes.pdf)

**For the graphs:** 
- We would like to have the date at the bottom of each graph we open, not just the day but the day+month.
- We'd like to have the max.y and min.y values moving with the highest and lowest values for each time period we choose.
- We would also like to be able to open each graph in full screen mode, as is possible with HydroVu.

**Annexe for situation map**
<img width="812" alt="Situation_map_background" src="https://github.com/user-attachments/assets/8ed40c0a-5bf5-4c86-81d8-e1ce2abbf9ac">

Let me know if something is not clear, I am available for a meeting or a zoom if needed

**Comment by AnderssonDan-epfl** [comment]
> Hello @charlottegiseleweil, **Here's a list of things we'd like to see changed on the web page and an image with some information on how we'd like to have it:**.
> 
> * The different types of sensor should be able to be activated, as is currently the case for the different layers (we want to be able to remove certain sensors from the map for better visualisation of the sensors we are interested in).
> * Modify the sensor labels --> picture below
> * Add automatic samplers below the sensors (--> picture below). For these, we would like to have a pop-up information when we click on them with a small description (Laboratory analysis of water samples for heavy metals, tyre abrasion residues and PFAS) and the information that the data from these are only on request (not displayed directly on the website).
> * Add dots on the title of the graph with the type of sensors that provide these data --> picture below
> * Change the name of the B sensors. It currently goes from B15 (upstream) to B1 (downstream) and we would like to have B1 (upstream) to B15 (downstream).
> * Need to add Ijinus C2 sensors
> * We want all the sensor points to be visible, without overlapping.
>   [waterportal_changes.pdf](https://github.com/user-attachments/files/16598880/waterportal_changes.pdf)
> 
> **For the graphs:**
> 
> * We would like to have the date at the bottom of each graph we open, not just the day but the day+month.
> * We'd like to have the max.y and min.y values moving with the highest and lowest values for each time period we choose.
> * We would also like to be able to open each graph in full screen mode, as is possible with HydroVu.
> 
> **Annexe for situation map** <img alt="Situation_map_background" width="812" src="https://private-user-images.githubusercontent.com/177507251/357394525-8ed40c0a-5bf5-4c86-81d8-e1ce2abbf9ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDk4ODYsIm5iZiI6MTcyMzU0OTU4NiwicGF0aCI6Ii8xNzc1MDcyNTEvMzU3Mzk0NTI1LThlZDQwYzBhLTViZjUtNGM4Ni04MWQ4LWUxY2UyYWJiZjlhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMTQ2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDgzNTQ2NzcxNDU3OTVjZTRlZmZjZDRhZWQxYjNjY2VmMjY0NDE5ZWQ2YzcxNWRkNDg1MGYzZDdiMGE3NWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hdARVDe6z4vfKlN3eEz96xEoIFGfj5rPK70gCSyiAlw">
> 
> Let me know if something is not clear, I am available for a meeting or a zoom if needed

it is in the pdf that you will find the changes that we want on the water portal

**Comment by AnderssonDan-epfl** [comment]
> Hello @AnderssonDan-epfl @RizlanBL you can provide here directly the points raised last week (listed under "Additonal information we need from researchers" in the comment above) when you get a chance ! Thank you very much !

Hi @charlottegiseleweil 
Here are some more information for the "Additional information we need from researchers"
- For "all parameters" I think you have title and units. For the description of the sensors, we are still not sure what we want to have. I will write down when we know.
- For the sliders it would be better to look with Paolo Perona or Giulio Calvani
- For the results also ask Paolo Perona or Giulio Calvani

Thank you

Dan

**Comment by ymarcon** [comment]
Dear @AnderssonDan-epfl 

* About "Modify the sensor labels --> picture below", where are these labels? I can only find A1, A2, B1 etc. names in the documents you provided
* About the "automatic samplers", where can I find detailed info about these?

**Comment by AnderssonDan-epfl** [comment]
> Dear @AnderssonDan-epfl
> 
> * About "Modify the sensor labels --> picture below", where are these labels? I can only find A1, A2, B1 etc. names in the documents you provided
> * About the "automatic samplers", where can I find detailed info about these?

Dear @ymarcon 
- For the  "Modify the sensor labels --> picture below" you already did it. I was maybe not clear enough but I wanted you to change the name of the sensors in the "Legends" 
- Sorry that I forgot to give you the information. Here under you can find the needed information : 
[Data informations.xlsx](https://github.com/user-attachments/files/16675216/Data.informations.xlsx)

**Comment by ymarcon** [comment]
@AnderssonDan-epfl Never mind, I found it

**Comment by AnderssonDan-epfl** [comment]
> @AnderssonDan-epfl do you have emplar data for the D sensors?

I am not sure what you mean by "emplar". Could you explain me what it is? @ymarcon

**Comment by AnderssonDan-epfl** [comment]
> oops: exemplar

@ymarcon I don't have some now, but as we won't make them appear on the website (only through request), is it really needed?

**Comment by ymarcon** [comment]
It is just for demonstration purposes, your choice.
